- name: setup mdns
  hosts: obake_hosts
  remote_user: root
  gather_facts: false

  tasks:
  - name: install avahi
    ansible.builtin.package:
      name: avahi-daemon
      state: present

- name: setup jack
  hosts: obake_hosts
  remote_user: root
  gather_facts: false

  tasks:
  - name: install jackd2
    ansible.builtin.package:
      name: jackd2
      state: present

- name: configure udev
  hosts: obake_hosts
  remote_user: root
  gather_facts: false

  tasks:
  - name: install usb_modeswitch
    ansible.builtin.package:
      name: usb-modeswitch
      state: present

  - name: copy udev rules
    ansible.builtin.copy:
      owner: root
      group: root
      mode: 0644
      src: "{{ item }}"
      dest: /etc/udev/rules.d/
    with_fileglob:
      - "../host/udev/*.rules"

  - name: install dev packages
    vars:
      # obake_env: "prod"
      packages:
      - libevdev-dev
      - liblo-dev
      - libudev-dev
      - libasound2-dev
      - libsndfile1-dev
      - libjack-jackd2-dev
    ansible.builtin.package:
      name: "{{ packages }}"
      state: present
    when: obake_env == "dev"


